### ISSUE TITLE
An option for selecting all columns

### ISSUE THREAD

**Issue by ghost** [sockeqwe/sqlbrite-dao#12]
In the `SELECT(String... columns)` it will be better if no arguments are accounted to all columns instead of throwing an exception, writing all column names can get tedious will be happy to do a PR for this

**Comment by sockeqwe** [comment]
I think it's good practice to only specify which columns you want to read to reduce the amount of loaded data.

Nevertheless, you can write `SELECT("*")` which is mor expressive since you know what "*" means

**Comment by ghost** [comment]
agrees, that works with the current logic as well added a javadoc comment to make this more obvious
#13

**Comment by sockeqwe** [comment]
thanks!
