### ISSUE TITLE
Mapper function which does not throw on missing column

### ISSUE THREAD

**Issue by ghost** [sockeqwe/sqlbrite-dao#20]
Since 0.4.0 it's not possible to not have a column in select since the mapper function throws an error

**Comment by ghost** [comment]
Since it is an rxjava function the only solution I see is to have a secondary function which doesn't thrown an exception

**Comment by sockeqwe** [comment]
What exactly do you mean with

> not possible to not have a column in select since 

can you post the generated mapper function  and a sample query?

**Comment by ghost** [comment]
Suppose the table has 3 columns and I select only two, the generated mapper
function throws an error because of cursor#getColumnIndexOrThrow as the
mapper tries get the index of every column this was not so by default in
the previous version

**Comment by sockeqwe** [comment]
I see ... That has been changed in `0.4.0` and is now configureable for each column via  Annotaion `@Column(throwOnColumnIndexNotFound = false)` (true is the default). The idea is to mark those columns as optional with `throwOnColumnIndexNotFound = false` ...

**Comment by ghost** [comment]
Got it
