### ISSUE TITLE
Dao Manager constructor should accept a listener

### ISSUE THREAD

**Issue by harinair** [sockeqwe/sqlbrite-dao#25]
Currently it is nice that the Dao's createTable and onUpgrade are invoked. However I may need to start something else: example a FullSync if DB is upgraded. I don't want to handle this in the Dao. I really would like to get a callback on DB Upgrade or create complete. I suggest that DaoManager allows argument CreationListener:

``` java
interface CreationListener {
     void onUpgradeComplete(int oldVersion, int newVersion);
     void onCreateComplete();
}
```

**Comment by sockeqwe** [comment]
Yep, will add that

harinair notifications@github.com schrieb am Di., 24. Nov. 2015, 04:43:

**Comment by harinair** [comment]
Thank you. Right now, I am creating a fake DAO and adding it as the last DAO to the DAO Manager.

Do you want me to work on this?

**Comment by sockeqwe** [comment]
I'm thinking about crrating the DaoManager with the Builder Pattern rather
then constructor because the number of construction parameters are
increasing and we may add even more options in the future. What do you
think?

harinair notifications@github.com schrieb am Mi., 25. Nov. 2015, 06:21:

**Comment by harinair** [comment]
Good idea.

**Comment by sockeqwe** [comment]
Introduced `DaoManager.Builder` which takes `TablesCreatedListener` and `TablesUpgradedListener` in version `0.5.0`
