### ISSUE TITLE
chain query

### ISSUE THREAD

**Issue by ziahaqi** [sockeqwe/sqlbrite-dao#33]
hi @sockeqwe i have a question, Can you tell me how to build a chained query ? ex:
...
Object a = getBy(id); //query 1
List<detail> details = getbyObjectId(int id);  //query 2
a.setDetail(details);
return a;

thanks

**Comment by sockeqwe** [comment]
- Either traditional SQL joins 

OR
- combining observables (since queries return `Observable<...>`) you can use for instance `combineLatest()` or even `.map()` or `flatMap()` depends on what exactly you want to build
