### ISSUE TITLE
No License specified

### ISSUE THREAD

**Issue by harinair** [sockeqwe/sqlbrite-dao#7]
Hannes:
I am thinking of evaluating sqlbrite for my work project. You seem to have not specified licensing terms. Without that I cannot use this project. Can you add a LICENSE.md/txt in the root folder? Normally the Apache and MIT licenses are blessed license. Anything other than that would create a hassle especially for mobile development.

**Comment by sockeqwe** [comment]
jep, apache 2 license ... I m currently updating to sqlbrite 0.3.0 and will
add the missing license file

harinair notifications@github.com schrieb am Sa., 5. Sep. 2015 08:19:
